import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const faqs = [
  {
    question: "Can AI really build my entire website?",
    answer:
      "Yes! Our advanced AI understands your business context and generates a complete, multi-page website including layout, copywriting, and relevant placeholder images that you can easily swap out.",
  },
  {
    question: "Do I need any coding experience?",
    answer:
      "None at all. A3TechWorld is designed for founders, marketers, and creators who want professional results without touching a single line of code. Our intuitive drag-and-drop editor handles the rest.",
  },
  {
    question: "Can I connect my own custom domain?",
    answer:
      "Absolutely. Pro and Enterprise plans allow you to connect any custom domain (e.g., yourcompany.com) with automatic SSL certification and lightning-fast global CDN hosting.",
  },
  {
    question: "Can I edit my website after it is generated?",
    answer:
      "Yes, your generated website is just the starting point. You have full control to edit text, swap images, add new sections, or even ask the AI to regenerate specific parts of a page.",
  },
  {
    question: "Are the generated websites mobile responsive?",
    answer:
      "100%. Every layout generated by A3TechWorld is inherently responsive, ensuring your site looks perfect on desktops, tablets, and mobile devices right out of the box.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggleAccordion = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-24 bg-brand-surface/30">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-5xl font-heading font-bold mb-6"
          >
            Frequently Asked Questions
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-lg text-brand-muted"
          >
            Got questions? We've got answers. If you don't see your question
            here, feel free to reach out.
          </motion.p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;

            return (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className={cn(
                  "border rounded-2xl overflow-hidden transition-colors duration-300",
                  isOpen
                    ? "bg-brand-surface border-brand-accent/50"
                    : "bg-brand-card border-brand-border hover:border-brand-text/30",
                )}
              >
                <button
                  onClick={() => toggleAccordion(index)}
                  className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
                >
                  <span className="font-heading font-semibold text-lg text-brand-text pr-8">
                    {faq.question}
                  </span>
                  <div
                    className={cn(
                      "w-8 h-8 rounded-full flex items-center justify-center shrink-0 transition-colors duration-300",
                      isOpen
                        ? "bg-brand-accent text-black"
                        : "bg-[#222] text-brand-muted",
                    )}
                  >
                    <ChevronDown
                      className={cn(
                        "w-5 h-5 transition-transform duration-300",
                        isOpen ? "rotate-180" : "",
                      )}
                    />
                  </div>
                </button>

                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3, ease: "easeInOut" }}
                    >
                      <div className="px-6 pb-6 pt-0 text-brand-muted leading-relaxed">
                        {faq.answer}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
